apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadapp
spec:
  selector:
    matchLabels:
      app: loadapp
  template:
    metadata:
      labels:
        app: loadapp
    spec:
      containers:
      - name: loadapp
        image: serkankaplan42/kubernetesloadtest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: load-service
spec:
  type: LoadBalancer
  selector:
    app: loadapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: horizontal-pod-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadapp
  minReplicas: 1
  maxReplicas: 999
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20


